//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JamesQuirks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JamesQuirks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes Eddie will stop whatever he&apos;s doing, get up, and open and close the cabinets around his house. He doesn&apos;t know why he does this. It could be because he needs a break or maybe he just gets bored..
        /// </summary>
        internal static string EddieQuirk1 {
            get {
                return ResourceManager.GetString("EddieQuirk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EddieQuirk1_jpg {
            get {
                object obj = ResourceManager.GetObject("EddieQuirk1_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eddie rambles to bounce ideas around. He doesn&apos;t need another person to do this.  Sometimes  he does this with other people around and it weirds them out. It&apos;s sort of like rubber ducky debugging..
        /// </summary>
        internal static string EddieQuirk2 {
            get {
                return ResourceManager.GetString("EddieQuirk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EddieQuirk2_jpg {
            get {
                object obj = ResourceManager.GetObject("EddieQuirk2_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JamesProfile_jpg {
            get {
                object obj = ResourceManager.GetObject("JamesProfile_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James&apos; favorite type of food is seafood. He enjoys cooking seafood himself  or eating out. His favorite dish is oysters on the halfshell, but he likes pretty much everything and is always excited to try new things..
        /// </summary>
        internal static string JamesQuirk1 {
            get {
                return ResourceManager.GetString("JamesQuirk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JamesQuirk1_jpg {
            get {
                object obj = ResourceManager.GetObject("JamesQuirk1_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to James owns a pet dog. His dog&apos;s name is Andy, he&apos;s six years old and he is a black Labrador retriever. Hames takes his dog to Ocean dog beach every weekend to enjoy some fun in the sun..
        /// </summary>
        internal static string JamesQuirk2 {
            get {
                return ResourceManager.GetString("JamesQuirk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JamesQuirk2_jpg {
            get {
                object obj = ResourceManager.GetObject("JamesQuirk2_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jim&apos;s gotten away from eggs, meat, toast/cereal breakfasts and instead eat steamed green leafy vegetables and pot boiled beans for all the nutrients and supposedly non cell degenerating properties of the greens and artery cleaning properties of the beans..
        /// </summary>
        internal static string JimQuirk1 {
            get {
                return ResourceManager.GetString("JimQuirk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JimQuirk1_jpg {
            get {
                object obj = ResourceManager.GetObject("JimQuirk1_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He takes his dog for about four mile walks every morning, usually starting around 5am, except when he procrastinate doing Professor Forman&apos;s assignments, which was pretty common last semester. Ugh!..
        /// </summary>
        internal static string JimQuirk2 {
            get {
                return ResourceManager.GetString("JimQuirk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JimQuirk2_jpg {
            get {
                object obj = ResourceManager.GetObject("JimQuirk2_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John is really forgetful. It usually takes more than a week to learn someone&apos;s name. He frequently forget my keys and/or phone when I leave the house and have forgotten my USB drive in this classroom more than once..
        /// </summary>
        internal static string JohnQuirk1 {
            get {
                return ResourceManager.GetString("JohnQuirk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JohnQuirk1_jpg {
            get {
                object obj = ResourceManager.GetObject("JohnQuirk1_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most of the music that John likes is in Japanese. He listens to Anime songs as well as vocaloids and medleys uploaded on the Niconico website..
        /// </summary>
        internal static string JohnQuirk2 {
            get {
                return ResourceManager.GetString("JohnQuirk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap JohnQuirk2_jpg {
            get {
                object obj = ResourceManager.GetObject("JohnQuirk2_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kevin thought for the longest time that he was allergic to shrimp despite having eaten it fine before. He had badly cooked shrimp two times in a row that made him sick each time and he stopped eating any shrimp for about 8 years..
        /// </summary>
        internal static string KevinQuirk1 {
            get {
                return ResourceManager.GetString("KevinQuirk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KevinQuirk1_jpg {
            get {
                object obj = ResourceManager.GetObject("KevinQuirk1_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kevin has over three dozen scarves and enjoys wearing them when he can.
        ///He has them sorted first by warmness, and then again by color..
        /// </summary>
        internal static string KevinQuirk2 {
            get {
                return ResourceManager.GetString("KevinQuirk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KevinQuirk2_jpg {
            get {
                object obj = ResourceManager.GetObject("KevinQuirk2_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap p1_bkg {
            get {
                object obj = ResourceManager.GetObject("p1_bkg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quentin tries to ride his bike as much as possible, but will often get flat tires or run into some other trouble, but it&apos;s worth it just to be able to ride his bike..
        /// </summary>
        internal static string QuentinQuirk1 {
            get {
                return ResourceManager.GetString("QuentinQuirk1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuentinQuirk1_jpg {
            get {
                object obj = ResourceManager.GetObject("QuentinQuirk1_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quentin also loves video games and will sometimes even play them even when I should be working or studying. He hopes that one day he can learn how to design his own games..
        /// </summary>
        internal static string QuentinQuirk2 {
            get {
                return ResourceManager.GetString("QuentinQuirk2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuentinQuirk2_jpg {
            get {
                object obj = ResourceManager.GetObject("QuentinQuirk2_jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_mark {
            get {
                object obj = ResourceManager.GetObject("question_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
